version: '3.3'

services:
    movefiles:
        build:
            args:
                CONTAINER_NAME: movefiles
                CONTAINER_VERSION: ${CONTAINER_VERSION:-3.0.0}
                FROM_BASE: perl-carton:${CONTAINER_TAG:-latest}
            cache_from:
                - alpine:3.8
                - base_container:${CONTAINER_TAG:-latest}
                - perl-5.26.2:${CONTAINER_TAG:-latest}
                - perl-carton:${CONTAINER_TAG:-latest}
            context: .
            dockerfile: Dockerfile
        container_name: moovefiles
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        hostname: movefiles
        image: movefiles:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3" 
                max-size: "10m"
#        restart: unless-stopped
        volumes:
            - ./:/usr/src/myapp
