version: '3.2'

services:
    movefiles:
        build:
            args:
                CODE_VERSION: perl-carton:20180210
            cache_from:
                - perl-carton:20180210
            context: .
        hostname: movefiles
        image: movefiles:20180210
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3" 
        restart: unless-stopped
        volumes:
            - ./:/usr/src/myapp
