version: '3.5'

services:
    movefiles:
        build:
            args:
                FROM_BASE: perl-carton:20180217
                CONTAINER_VERSION: 1.0.2
            cache_from:
                - perl-carton:20180217
                - perl-5.24.3:20180217
                - base_container:20180217
                - alpine:3.6                 
            context: .
        hostname: movefiles
        image: movefiles:20180217
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3" 
        restart: unless-stopped
        volumes:
            - ./:/usr/src/myapp

    base:
        build:
            args:
                FROM_BASE: alpine:3.6
                CONTAINER_VERSION: 1.0.2
                TZ: "America/New_York"
            cache_from:
                - alpine:3.6
            context: ../base_container
        image: base_container:20180217

    carton:
        build:
            args:
                FROM_BASE: perl-5.24.3:20180217
                CONTAINER_VERSION: 1.0.2
            cache_from:
                - perl-5.24.3:20180217
                - base_container:20180217
                - alpine:3.6
            context: ../perl-carton
        image: perl-carton:20180217

    perl:
        build:
            args:
                FROM_BASE: base_container:20180217
                CONTAINER_VERSION: 1.0.2
            cache_from:
                - base_container:20180217
            context: ../perl.5-24-3
        image: perl-5.24.3:20180217 