version: '3.5'

services:
    movefiles:
        build:
            args:
                CONTAINER_VERSION: 1.0.2
                DEBUG_TRACE: 0
                FROM_BASE: perl-carton:20180217
            cache_from:
                - perl-carton:20180217
                - perl-5.24.3:20180217
                - base_container:20180217
                - alpine:3.6                 
            context: .
            dockerfile: Dockerfile
        environment:
            CONTAINER_NAME: movefiles 
        hostname: movefiles
        image: movefiles:20180217
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3" 
#        restart: unless-stopped
        volumes:
            - ./:/usr/src/myapp
