version: '3.3'

services:
    movefiles:
        build:
            args:
                CONTAINER_NAME: movefiles
                FROM_BASE: ${DOCKER_REGISTRY:-}perl-carton:${BASE_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}perl:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}perl-carton:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.branch: $CONTAINER_GIT_BRANCH
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: movefiles
        container_name: moovefiles
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        hostname: movefiles
        image: ${DOCKER_REGISTRY:-}movefiles:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
#        restart: unless-stopped
        volumes:
            - ./:/usr/src/myapp
