version: '3.5'

services:
    movefiles:
        build:
            args:
                CODE_VERSION: perl-carton:20180210
            cache_from:
                - perl-carton:20180210
                - perl-5.24.3:20180210
                - base_container:20180210
                - alpine:3.6                 
            context: .
#        depends_on:
#            - carton
        hostname: movefiles
        image: movefiles:20180210
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3" 
        restart: unless-stopped
        volumes:
            - ./:/usr/src/myapp
