version: '3.5'

services:
    movefiles:
        build:
            args:
                CONTAINER_NAME: movefiles 
                CONTAINER_VERSION: 1.0.5
                DEBUG_TRACE: 0
                FROM_BASE: perl-carton:20180311
            cache_from:
                - perl-carton:20180311
                - perl-5.24.3:20180311
                - base_container:20180311
                - alpine:3.6                 
            context: .
            dockerfile: Dockerfile
        hostname: movefiles
        image: movefiles:20180311
        logging:
            driver: json-file
            options:
                max-file: "3" 
                max-size: "10m"
#        restart: unless-stopped
        volumes:
            - ./:/usr/src/myapp
